/* AUTO-GENERATED by scripts/extract-evidence.mjs — do not hand-edit.
 * Source: app/frontend/assets/index-DTKnr6h1.js
 * SHA256: a5352227d053c92889a615be1b30774c8e852dddb43f9f06235e7285ab1d923c
 */
export const EVIDENCE_SOURCE = {
  path: "C:/Users/darbot/Downloads/opentrader-dev/AgentTrader/app/frontend/assets/index-DTKnr6h1.js",
  relative: "../../app/frontend/assets/index-DTKnr6h1.js",
  sha256: "a5352227d053c92889a615be1b30774c8e852dddb43f9f06235e7285ab1d923c",
  bytes: 8693186,
  lines: 249814,
} as const;

export type EvidenceRef = {
  id: string;
  file: string | null;
  line: number | null;
  ref: string | null;
  excerpt: string | null;
  status: "ok" | "missing";
};

export const CLAIMS = {
  "meta.app_title": {
    "id": "meta.app_title",
    "file": "index-DTKnr6h1.js",
    "line": 43712,
    "ref": "index-DTKnr6h1.js:43712",
    "excerpt": "    [s, i] = V.useState(\"agentrader\"),",
    "status": "ok"
  },
  "meta.backend_default": {
    "id": "meta.backend_default",
    "file": "index-DTKnr6h1.js",
    "line": 25907,
    "ref": "index-DTKnr6h1.js:25907",
    "excerpt": "  XD = \"http://localhost:8000\";",
    "status": "ok"
  },
  "meta.api_trpc": {
    "id": "meta.api_trpc",
    "file": "index-DTKnr6h1.js",
    "line": 32402,
    "ref": "index-DTKnr6h1.js:32402",
    "excerpt": "              url: `${w8()}/api/trpc`,",
    "status": "ok"
  },
  "storage.APP_URL": {
    "id": "storage.APP_URL",
    "file": "index-DTKnr6h1.js",
    "line": 25904,
    "ref": "index-DTKnr6h1.js:25904",
    "excerpt": "const gA = \"APP_URL\",",
    "status": "ok"
  },
  "storage.ADMIN_PASSWORD": {
    "id": "storage.ADMIN_PASSWORD",
    "file": "index-DTKnr6h1.js",
    "line": 25905,
    "ref": "index-DTKnr6h1.js:25905",
    "excerpt": "  yB = \"ADMIN_PASSWORD\",",
    "status": "ok"
  },
  "storage.DEVELOPER_MODE_ENABLED": {
    "id": "storage.DEVELOPER_MODE_ENABLED",
    "file": "index-DTKnr6h1.js",
    "line": 25906,
    "ref": "index-DTKnr6h1.js:25906",
    "excerpt": "  hM = \"DEVELOPER_MODE_ENABLED\",",
    "status": "ok"
  },
  "ui.login.welcome": {
    "id": "ui.login.welcome",
    "file": "index-DTKnr6h1.js",
    "line": 43732,
    "ref": "index-DTKnr6h1.js:43732",
    "excerpt": "      P.jsx(Ct, { component: \"h1\", level: \"h4\", children: \"Welcome Trader!\" }),",
    "status": "ok"
  },
  "ui.login.sign_in": {
    "id": "ui.login.sign_in",
    "file": "index-DTKnr6h1.js",
    "line": 43733,
    "ref": "index-DTKnr6h1.js:43733",
    "excerpt": "      P.jsx(Ct, { level: \"body-sm\", children: \"Sign in to continue.\" }),",
    "status": "ok"
  },
  "ui.login.backend_url": {
    "id": "ui.login.backend_url",
    "file": "index-DTKnr6h1.js",
    "line": 36797,
    "ref": "index-DTKnr6h1.js:36797",
    "excerpt": "        P.jsx(jm, { children: P.jsxs(tn, { children: [P.jsx(Pn, { children: \"Backend URL\" }), P.jsx(Z8, {})] }) }),",
    "status": "ok"
  },
  "ui.login.username": {
    "id": "ui.login.username",
    "file": "index-DTKnr6h1.js",
    "line": 43748,
    "ref": "index-DTKnr6h1.js:43748",
    "excerpt": "          P.jsx(Pn, { children: \"Username\" }),",
    "status": "ok"
  },
  "ui.login.password": {
    "id": "ui.login.password",
    "file": "index-DTKnr6h1.js",
    "line": 43760,
    "ref": "index-DTKnr6h1.js:43760",
    "excerpt": "          P.jsx(Pn, { children: \"Password\" }),",
    "status": "ok"
  },
  "ui.login.submit": {
    "id": "ui.login.submit",
    "file": "index-DTKnr6h1.js",
    "line": 43774,
    "ref": "index-DTKnr6h1.js:43774",
    "excerpt": "      P.jsx(yi, { onClick: o, sx: { mt: 1 }, children: \"Log in\" }),",
    "status": "ok"
  },
  "ui.nav.bots": {
    "id": "ui.nav.bots",
    "file": "index-DTKnr6h1.js",
    "line": 37537,
    "ref": "index-DTKnr6h1.js:37537",
    "excerpt": "        P.jsx(Pv, { href: Js(\"bot\"), icon: P.jsx(tG, {}), size: c, onClick: e, children: \"Bots\" }),",
    "status": "ok"
  },
  "ui.nav.strategies": {
    "id": "ui.nav.strategies",
    "file": "index-DTKnr6h1.js",
    "line": 37538,
    "ref": "index-DTKnr6h1.js:37538",
    "excerpt": "        P.jsx(Pv, { href: Js(\"strategies\"), icon: P.jsx(Fpe, {}), size: c, onClick: e, children: \"Strategies\" }),",
    "status": "ok"
  },
  "ui.nav.accounts": {
    "id": "ui.nav.accounts",
    "file": "index-DTKnr6h1.js",
    "line": 37539,
    "ref": "index-DTKnr6h1.js:37539",
    "excerpt": "        P.jsx(Pv, { href: Js(\"accounts\"), icon: P.jsx(qpe, {}), size: c, onClick: e, children: \"Exchange Accounts\" }),",
    "status": "ok"
  },
  "ui.nav.settings": {
    "id": "ui.nav.settings",
    "file": "index-DTKnr6h1.js",
    "line": 37509,
    "ref": "index-DTKnr6h1.js:37509",
    "excerpt": "    \"Settings\",",
    "status": "ok"
  },
  "ui.settings.title": {
    "id": "ui.settings.title",
    "file": "index-DTKnr6h1.js",
    "line": 43705,
    "ref": "index-DTKnr6h1.js:43705",
    "excerpt": "      children: [P.jsx(Ct, { level: \"h3\", children: \"App settings\" }), P.jsx(rwe, {}), P.jsx(iwe, {}), P.jsx(nwe, {})],",
    "status": "ok"
  },
  "ui.msg.bot_created": {
    "id": "ui.msg.bot_created",
    "file": "index-DTKnr6h1.js",
    "line": 237609,
    "ref": "index-DTKnr6h1.js:237609",
    "excerpt": "          c(\"Bot created successfully\"),",
    "status": "ok"
  },
  "ui.msg.bot_updated": {
    "id": "ui.msg.bot_updated",
    "file": "index-DTKnr6h1.js",
    "line": 249572,
    "ref": "index-DTKnr6h1.js:249572",
    "excerpt": "          a(\"Bot updated successfully\"),",
    "status": "ok"
  },
  "ui.msg.no_logs": {
    "id": "ui.msg.no_logs",
    "file": "index-DTKnr6h1.js",
    "line": 47466,
    "ref": "index-DTKnr6h1.js:47466",
    "excerpt": "          children: \"No logs yet\",",
    "status": "ok"
  },
  "ui.msg.account_created": {
    "id": "ui.msg.account_created",
    "file": "index-DTKnr6h1.js",
    "line": 46816,
    "ref": "index-DTKnr6h1.js:46816",
    "excerpt": "              s(), t(), i(\"Account created\");",
    "status": "ok"
  },
  "ui.msg.account_checked": {
    "id": "ui.msg.account_checked",
    "file": "index-DTKnr6h1.js",
    "line": 44775,
    "ref": "index-DTKnr6h1.js:44775",
    "excerpt": "            ? e(\"Account checked. Credentials are valid.\")",
    "status": "ok"
  },
  "ui.msg.add_exchange": {
    "id": "ui.msg.add_exchange",
    "file": "index-DTKnr6h1.js",
    "line": 47349,
    "ref": "index-DTKnr6h1.js:47349",
    "excerpt": "            children: \"Add exchange account\",",
    "status": "ok"
  },
  "ui.msg.bot_settings": {
    "id": "ui.msg.bot_settings",
    "file": "index-DTKnr6h1.js",
    "line": 243590,
    "ref": "index-DTKnr6h1.js:243590",
    "excerpt": "            P.jsx(Ct, { level: \"h2\", sx: { mb: 1 }, children: \"Bot settings\" }),",
    "status": "ok"
  },
  "ui.msg.create": {
    "id": "ui.msg.create",
    "file": "index-DTKnr6h1.js",
    "line": 46791,
    "ref": "index-DTKnr6h1.js:46791",
    "excerpt": "                        children: \"Create\",",
    "status": "ok"
  },
  "ui.strategy.grid": {
    "id": "ui.strategy.grid",
    "file": "index-DTKnr6h1.js",
    "line": 43593,
    "ref": "index-DTKnr6h1.js:43593",
    "excerpt": "  return c.displayName === \"Grid Bot\" || c.displayName === \"DCA Bot\";",
    "status": "ok"
  },
  "ui.strategy.dca": {
    "id": "ui.strategy.dca",
    "file": "index-DTKnr6h1.js",
    "line": 43593,
    "ref": "index-DTKnr6h1.js:43593",
    "excerpt": "  return c.displayName === \"Grid Bot\" || c.displayName === \"DCA Bot\";",
    "status": "ok"
  },
  "form.default.symbol": {
    "id": "form.default.symbol",
    "file": "index-DTKnr6h1.js",
    "line": 21104,
    "ref": "index-DTKnr6h1.js:21104",
    "excerpt": "    symbolId: \"OKX:BTC/USDT\",",
    "status": "ok"
  },
  "form.default.exchange": {
    "id": "form.default.exchange",
    "file": "index-DTKnr6h1.js",
    "line": 18515,
    "ref": "index-DTKnr6h1.js:18515",
    "excerpt": "    OKX: \"OKX\",",
    "status": "ok"
  },
  "form.slice.gridBotForm": {
    "id": "form.slice.gridBotForm",
    "file": "index-DTKnr6h1.js",
    "line": 21114,
    "ref": "index-DTKnr6h1.js:21114",
    "excerpt": "    name: \"gridBotForm\",",
    "status": "ok"
  },
  "form.slice.dcaBotForm": {
    "id": "form.slice.dcaBotForm",
    "file": "index-DTKnr6h1.js",
    "line": 21677,
    "ref": "index-DTKnr6h1.js:21677",
    "excerpt": "    name: \"dcaBotForm\",",
    "status": "ok"
  },
  "form.field.highPrice": {
    "id": "form.field.highPrice",
    "file": "index-DTKnr6h1.js",
    "line": 21106,
    "ref": "index-DTKnr6h1.js:21106",
    "excerpt": "    highPrice: 0,",
    "status": "ok"
  },
  "form.field.lowPrice": {
    "id": "form.field.lowPrice",
    "file": "index-DTKnr6h1.js",
    "line": 21107,
    "ref": "index-DTKnr6h1.js:21107",
    "excerpt": "    lowPrice: 0,",
    "status": "ok"
  },
  "form.field.gridLines": {
    "id": "form.field.gridLines",
    "file": "index-DTKnr6h1.js",
    "line": 21094,
    "ref": "index-DTKnr6h1.js:21094",
    "excerpt": "Tu({ gridLines: rB(Ise) });",
    "status": "ok"
  },
  "form.field.quantityPerGrid": {
    "id": "form.field.quantityPerGrid",
    "file": "index-DTKnr6h1.js",
    "line": 21109,
    "ref": "index-DTKnr6h1.js:21109",
    "excerpt": "    quantityPerGrid: `${_se}`,",
    "status": "ok"
  },
  "form.field.gridLinesNumber": {
    "id": "form.field.gridLinesNumber",
    "file": "index-DTKnr6h1.js",
    "line": 21108,
    "ref": "index-DTKnr6h1.js:21108",
    "excerpt": "    gridLinesNumber: Cse,",
    "status": "ok"
  },
  "form.field.safetyOrders": {
    "id": "form.field.safetyOrders",
    "file": "index-DTKnr6h1.js",
    "line": 21076,
    "ref": "index-DTKnr6h1.js:21076",
    "excerpt": "  safetyOrders: rB(",
    "status": "ok"
  },
  "form.field.takeProfitPercent": {
    "id": "form.field.takeProfitPercent",
    "file": "index-DTKnr6h1.js",
    "line": 21663,
    "ref": "index-DTKnr6h1.js:21663",
    "excerpt": "    takeProfitPercent: _H,",
    "status": "ok"
  },
  "form.field.stopLossPercent": {
    "id": "form.field.stopLossPercent",
    "file": "index-DTKnr6h1.js",
    "line": 21665,
    "ref": "index-DTKnr6h1.js:21665",
    "excerpt": "    stopLossPercent: MH,",
    "status": "ok"
  },
  "form.field.stopLossEnabled": {
    "id": "form.field.stopLossEnabled",
    "file": "index-DTKnr6h1.js",
    "line": 21664,
    "ref": "index-DTKnr6h1.js:21664",
    "excerpt": "    stopLossEnabled: !1,",
    "status": "ok"
  },
  "form.field.botName": {
    "id": "form.field.botName",
    "file": "index-DTKnr6h1.js",
    "line": 21101,
    "ref": "index-DTKnr6h1.js:21101",
    "excerpt": "    botName: \"\",",
    "status": "ok"
  },
  "form.field.exchangeAccountId": {
    "id": "form.field.exchangeAccountId",
    "file": "index-DTKnr6h1.js",
    "line": 21102,
    "ref": "index-DTKnr6h1.js:21102",
    "excerpt": "    exchangeAccountId: 0,",
    "status": "ok"
  },
  "form.field.symbolId": {
    "id": "form.field.symbolId",
    "file": "index-DTKnr6h1.js",
    "line": 21104,
    "ref": "index-DTKnr6h1.js:21104",
    "excerpt": "    symbolId: \"OKX:BTC/USDT\",",
    "status": "ok"
  },
  "form.field.barSize": {
    "id": "form.field.barSize",
    "file": "index-DTKnr6h1.js",
    "line": 21111,
    "ref": "index-DTKnr6h1.js:21111",
    "excerpt": "    barSize: B0.ONE_DAY,",
    "status": "ok"
  },
  "route.file.layout": {
    "id": "route.file.layout",
    "file": "index-DTKnr6h1.js",
    "line": 37878,
    "ref": "index-DTKnr6h1.js:37878",
    "excerpt": "  nme = ea(\"/_layout\")({ component: rme });",
    "status": "ok"
  },
  "route.file.bot_edit": {
    "id": "route.file.bot_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249634,
    "ref": "index-DTKnr6h1.js:249634",
    "excerpt": "const Yz = ea(\"/_layout/dashboard/bot/edit/$id\")({ component: gVe }),",
    "status": "ok"
  },
  "route.file.grid_create": {
    "id": "route.file.grid_create",
    "file": "index-DTKnr6h1.js",
    "line": 47455,
    "ref": "index-DTKnr6h1.js:47455",
    "excerpt": "  Qke = ea(\"/_layout/dashboard/grid-bot/create\")({ component: Xke });",
    "status": "ok"
  },
  "route.file.grid_edit": {
    "id": "route.file.grid_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249552,
    "ref": "index-DTKnr6h1.js:249552",
    "excerpt": "  lVe = ea(\"/_layout/dashboard/grid-bot/edit/$id\")({ component: uVe }),",
    "status": "ok"
  },
  "route.file.dca_create": {
    "id": "route.file.dca_create",
    "file": "index-DTKnr6h1.js",
    "line": 243636,
    "ref": "index-DTKnr6h1.js:243636",
    "excerpt": "const m5e = ea(\"/_layout/dashboard/dca-bot/create\")({ component: p5e }),",
    "status": "ok"
  },
  "route.file.dca_edit": {
    "id": "route.file.dca_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249554,
    "ref": "index-DTKnr6h1.js:249554",
    "excerpt": "  fVe = ea(\"/_layout/dashboard/dca-bot/edit/$id\")({ component: hVe });",
    "status": "ok"
  },
  "route.file.login": {
    "id": "route.file.login",
    "file": "index-DTKnr6h1.js",
    "line": 43778,
    "ref": "index-DTKnr6h1.js:43778",
    "excerpt": "const cwe = ea(\"/_layout/dashboard/login\")({ component: dwe }),",
    "status": "ok"
  },
  "route.file.accounts": {
    "id": "route.file.accounts",
    "file": "index-DTKnr6h1.js",
    "line": 47013,
    "ref": "index-DTKnr6h1.js:47013",
    "excerpt": "const Ake = ea(\"/_layout/dashboard/accounts\")({ component: Mke }),",
    "status": "ok"
  },
  "route.file.settings": {
    "id": "route.file.settings",
    "file": "index-DTKnr6h1.js",
    "line": 43709,
    "ref": "index-DTKnr6h1.js:43709",
    "excerpt": "const owe = ea(\"/_layout/dashboard/settings\")({ component: awe });",
    "status": "ok"
  },
  "route.file.strategies": {
    "id": "route.file.strategies",
    "file": "index-DTKnr6h1.js",
    "line": 43673,
    "ref": "index-DTKnr6h1.js:43673",
    "excerpt": "const swe = ea(\"/_layout/dashboard/strategies\")({ component: twe });",
    "status": "ok"
  },
  "route.file.bot_index": {
    "id": "route.file.bot_index",
    "file": "index-DTKnr6h1.js",
    "line": 47368,
    "ref": "index-DTKnr6h1.js:47368",
    "excerpt": "const zke = ea(\"/_layout/dashboard/bot/\")({ component: jke }),",
    "status": "ok"
  },
  "route.file.bot_id": {
    "id": "route.file.bot_id",
    "file": "index-DTKnr6h1.js",
    "line": 249545,
    "ref": "index-DTKnr6h1.js:249545",
    "excerpt": "const Qz = ea(\"/_layout/dashboard/bot/$id\")({",
    "status": "ok"
  },
  "route.file.bot_create": {
    "id": "route.file.bot_create",
    "file": "index-DTKnr6h1.js",
    "line": 249353,
    "ref": "index-DTKnr6h1.js:249353",
    "excerpt": "const Xz = ea(\"/_layout/dashboard/bot/create\")({",
    "status": "ok"
  },
  "route.file.grid_id": {
    "id": "route.file.grid_id",
    "file": "index-DTKnr6h1.js",
    "line": 237281,
    "ref": "index-DTKnr6h1.js:237281",
    "excerpt": "const J7 = ea(\"/_layout/dashboard/grid-bot/$id\")({",
    "status": "ok"
  },
  "route.file.dca_id": {
    "id": "route.file.dca_id",
    "file": "index-DTKnr6h1.js",
    "line": 243764,
    "ref": "index-DTKnr6h1.js:243764",
    "excerpt": "const Dz = ea(\"/_layout/dashboard/dca-bot/$id\")({",
    "status": "ok"
  },
  "route.path.bot_edit": {
    "id": "route.path.bot_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249634,
    "ref": "index-DTKnr6h1.js:249634",
    "excerpt": "const Yz = ea(\"/_layout/dashboard/bot/edit/$id\")({ component: gVe }),",
    "status": "ok"
  },
  "route.path.grid_create": {
    "id": "route.path.grid_create",
    "file": "index-DTKnr6h1.js",
    "line": 32360,
    "ref": "index-DTKnr6h1.js:32360",
    "excerpt": "  \"grid-bot/create\": \"/dashboard/grid-bot/create\",",
    "status": "ok"
  },
  "route.path.grid_edit": {
    "id": "route.path.grid_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249552,
    "ref": "index-DTKnr6h1.js:249552",
    "excerpt": "  lVe = ea(\"/_layout/dashboard/grid-bot/edit/$id\")({ component: uVe }),",
    "status": "ok"
  },
  "route.path.dca_create": {
    "id": "route.path.dca_create",
    "file": "index-DTKnr6h1.js",
    "line": 32363,
    "ref": "index-DTKnr6h1.js:32363",
    "excerpt": "  \"dca-bot/create\": \"/dashboard/dca-bot/create\",",
    "status": "ok"
  },
  "route.path.login": {
    "id": "route.path.login",
    "file": "index-DTKnr6h1.js",
    "line": 32349,
    "ref": "index-DTKnr6h1.js:32349",
    "excerpt": "  login: \"/dashboard/login\",",
    "status": "ok"
  },
  "route.key.LayoutDashboardBotEditIdRoute": {
    "id": "route.key.LayoutDashboardBotEditIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249671,
    "ref": "index-DTKnr6h1.js:249671",
    "excerpt": "    LayoutDashboardBotEditIdRoute: AVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardGridBotCreateRoute": {
    "id": "route.key.LayoutDashboardGridBotCreateRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249669,
    "ref": "index-DTKnr6h1.js:249669",
    "excerpt": "    LayoutDashboardGridBotCreateRoute: TVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardDcaBotEditIdRoute": {
    "id": "route.key.LayoutDashboardDcaBotEditIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249672,
    "ref": "index-DTKnr6h1.js:249672",
    "excerpt": "    LayoutDashboardDcaBotEditIdRoute: MVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardAccountsRoute": {
    "id": "route.key.LayoutDashboardAccountsRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249660,
    "ref": "index-DTKnr6h1.js:249660",
    "excerpt": "    LayoutDashboardAccountsRoute: SVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardLoginRoute": {
    "id": "route.key.LayoutDashboardLoginRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249661,
    "ref": "index-DTKnr6h1.js:249661",
    "excerpt": "    LayoutDashboardLoginRoute: kVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardSettingsRoute": {
    "id": "route.key.LayoutDashboardSettingsRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249662,
    "ref": "index-DTKnr6h1.js:249662",
    "excerpt": "    LayoutDashboardSettingsRoute: bVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardStrategiesRoute": {
    "id": "route.key.LayoutDashboardStrategiesRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249663,
    "ref": "index-DTKnr6h1.js:249663",
    "excerpt": "    LayoutDashboardStrategiesRoute: wVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardBotIndexRoute": {
    "id": "route.key.LayoutDashboardBotIndexRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249670,
    "ref": "index-DTKnr6h1.js:249670",
    "excerpt": "    LayoutDashboardBotIndexRoute: vVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardBotIdRoute": {
    "id": "route.key.LayoutDashboardBotIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249664,
    "ref": "index-DTKnr6h1.js:249664",
    "excerpt": "    LayoutDashboardBotIdRoute: CVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardBotCreateRoute": {
    "id": "route.key.LayoutDashboardBotCreateRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249665,
    "ref": "index-DTKnr6h1.js:249665",
    "excerpt": "    LayoutDashboardBotCreateRoute: IVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardGridBotIdRoute": {
    "id": "route.key.LayoutDashboardGridBotIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249668,
    "ref": "index-DTKnr6h1.js:249668",
    "excerpt": "    LayoutDashboardGridBotIdRoute: OVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardGridBotEditIdRoute": {
    "id": "route.key.LayoutDashboardGridBotEditIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249673,
    "ref": "index-DTKnr6h1.js:249673",
    "excerpt": "    LayoutDashboardGridBotEditIdRoute: _Ve,",
    "status": "ok"
  },
  "route.key.LayoutDashboardDcaBotIdRoute": {
    "id": "route.key.LayoutDashboardDcaBotIdRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249666,
    "ref": "index-DTKnr6h1.js:249666",
    "excerpt": "    LayoutDashboardDcaBotIdRoute: PVe,",
    "status": "ok"
  },
  "route.key.LayoutDashboardDcaBotCreateRoute": {
    "id": "route.key.LayoutDashboardDcaBotCreateRoute",
    "file": "index-DTKnr6h1.js",
    "line": 249667,
    "ref": "index-DTKnr6h1.js:249667",
    "excerpt": "    LayoutDashboardDcaBotCreateRoute: xVe,",
    "status": "ok"
  },
  "rpc.public.healhcheck": {
    "id": "rpc.public.healhcheck",
    "file": "index-DTKnr6h1.js",
    "line": 36809,
    "ref": "index-DTKnr6h1.js:36809",
    "excerpt": "      } = mB(e.public.healhcheck.queryOptions(void 0, { retry: !1, refetchOnWindowFocus: !1 }));",
    "status": "ok"
  },
  "rpc.bot.list": {
    "id": "rpc.bot.list",
    "file": "index-DTKnr6h1.js",
    "line": 47025,
    "ref": "index-DTKnr6h1.js:47025",
    "excerpt": "          r.invalidateQueries(n.bot.list.queryOptions()),",
    "status": "ok"
  },
  "rpc.bot.getOne": {
    "id": "rpc.bot.getOne",
    "file": "index-DTKnr6h1.js",
    "line": 47024,
    "ref": "index-DTKnr6h1.js:47024",
    "excerpt": "          r.invalidateQueries(n.bot.getOne.queryOptions(t.id)),",
    "status": "ok"
  },
  "rpc.bot.start": {
    "id": "rpc.bot.start",
    "file": "index-DTKnr6h1.js",
    "line": 47030,
    "ref": "index-DTKnr6h1.js:47030",
    "excerpt": "        n.bot.start.mutationOptions({",
    "status": "ok"
  },
  "rpc.bot.stop": {
    "id": "rpc.bot.stop",
    "file": "index-DTKnr6h1.js",
    "line": 47037,
    "ref": "index-DTKnr6h1.js:47037",
    "excerpt": "        n.bot.stop.mutationOptions({",
    "status": "ok"
  },
  "rpc.bot.getStrategies": {
    "id": "rpc.bot.getStrategies",
    "file": "index-DTKnr6h1.js",
    "line": 43654,
    "ref": "index-DTKnr6h1.js:43654",
    "excerpt": "    { data: t } = Rs(c.bot.getStrategies.queryOptions()),",
    "status": "ok"
  },
  "rpc.gridBot.create": {
    "id": "rpc.gridBot.create",
    "file": "page-B7EduWBL.js",
    "line": 66,
    "ref": "page-B7EduWBL.js:66",
    "excerpt": "        n.gridBot.create.mutationOptions({",
    "status": "ok"
  },
  "rpc.gridBot.update": {
    "id": "rpc.gridBot.update",
    "file": "page-Dps6Us_X.js",
    "line": 72,
    "ref": "page-Dps6Us_X.js:72",
    "excerpt": "        e.gridBot.update.mutationOptions({",
    "status": "ok"
  },
  "rpc.gridBot.getOne": {
    "id": "rpc.gridBot.getOne",
    "file": "index-DTKnr6h1.js",
    "line": 47023,
    "ref": "index-DTKnr6h1.js:47023",
    "excerpt": "        r.invalidateQueries(n.gridBot.getOne.queryOptions(t.id)),",
    "status": "ok"
  },
  "rpc.gridBot.formOptions": {
    "id": "rpc.gridBot.formOptions",
    "file": "page-B7EduWBL.js",
    "line": 102,
    "ref": "page-B7EduWBL.js:102",
    "excerpt": "      o.gridBot.formOptions.queryOptions({ symbolId: n, isDemoAccount: c }, { refetchOnWindowFocus: !1 }),",
    "status": "ok"
  },
  "rpc.dcaBot.create": {
    "id": "rpc.dcaBot.create",
    "file": "index-DTKnr6h1.js",
    "line": 237607,
    "ref": "index-DTKnr6h1.js:237607",
    "excerpt": "      s.dcaBot.create.mutationOptions({",
    "status": "ok"
  },
  "rpc.dcaBot.getOne": {
    "id": "rpc.dcaBot.getOne",
    "file": "index-DTKnr6h1.js",
    "line": 47751,
    "ref": "index-DTKnr6h1.js:47751",
    "excerpt": "          i.invalidateQueries(s.dcaBot.getOne.queryOptions(e.id)),",
    "status": "ok"
  },
  "rpc.dcaBot.update": {
    "id": "rpc.dcaBot.update",
    "file": "page-CAOt1VfL.js",
    "line": 74,
    "ref": "page-CAOt1VfL.js:74",
    "excerpt": "      t.dcaBot.update.mutationOptions({",
    "status": "ok"
  },
  "rpc.exchangeAccount.list": {
    "id": "rpc.exchangeAccount.list",
    "file": "index-DTKnr6h1.js",
    "line": 43653,
    "ref": "index-DTKnr6h1.js:43653",
    "excerpt": "    { data: e } = Rs(c.exchangeAccount.list.queryOptions()),",
    "status": "ok"
  },
  "rpc.exchangeAccount.create": {
    "id": "rpc.exchangeAccount.create",
    "file": "index-DTKnr6h1.js",
    "line": 46722,
    "ref": "index-DTKnr6h1.js:46722",
    "excerpt": "      } = Xo(i.exchangeAccount.create.mutationOptions());",
    "status": "ok"
  },
  "rpc.symbol.list": {
    "id": "rpc.symbol.list",
    "file": "index-DTKnr6h1.js",
    "line": 236447,
    "ref": "index-DTKnr6h1.js:236447",
    "excerpt": "      { data: d } = Rs(r.symbol.list.queryOptions({ exchangeCode: c, isDemoAccount: e }, { initialData: i }));",
    "status": "ok"
  },
  "rpc.symbol.getOne": {
    "id": "rpc.symbol.getOne",
    "file": "index-DTKnr6h1.js",
    "line": 235549,
    "ref": "index-DTKnr6h1.js:235549",
    "excerpt": "      { data: u } = Rs(d.symbol.getOne.queryOptions({ symbolId: c, isDemoAccount: e })),",
    "status": "ok"
  },
  "rpc.symbol.price": {
    "id": "rpc.symbol.price",
    "file": "index-DTKnr6h1.js",
    "line": 237714,
    "ref": "index-DTKnr6h1.js:237714",
    "excerpt": "      } = Rs(e.symbol.price.queryOptions({ symbolId: i.symbolId, isDemoAccount: s.isDemoAccount })),",
    "status": "ok"
  },
  "tool.vite.mapDeps": {
    "id": "tool.vite.mapDeps",
    "file": "index-DTKnr6h1.js",
    "line": 1,
    "ref": "index-DTKnr6h1.js:1",
    "excerpt": "const __vite__mapDeps = (",
    "status": "ok"
  },
  "tool.react.createRoot": {
    "id": "tool.react.createRoot",
    "file": "index-DTKnr6h1.js",
    "line": 8037,
    "ref": "index-DTKnr6h1.js:8037",
    "excerpt": "    (Eo.createRoot = function (w, S) {",
    "status": "ok"
  },
  "tool.react.StrictMode": {
    "id": "tool.react.StrictMode",
    "file": "index-DTKnr6h1.js",
    "line": 351,
    "ref": "index-DTKnr6h1.js:351",
    "excerpt": "    (Zs.StrictMode = s),",
    "status": "ok"
  },
  "tool.chunk.grid_create": {
    "id": "tool.chunk.grid_create",
    "file": "index-DTKnr6h1.js",
    "line": 6,
    "ref": "index-DTKnr6h1.js:6",
    "excerpt": "      \"assets/page-B7EduWBL.js\",",
    "status": "ok"
  },
  "tool.chunk.simple_grid": {
    "id": "tool.chunk.simple_grid",
    "file": "index-DTKnr6h1.js",
    "line": 7,
    "ref": "index-DTKnr6h1.js:7",
    "excerpt": "      \"assets/SimpleGridForm-BUsQPU4Z.js\",",
    "status": "ok"
  },
  "tool.chunk.grid_edit": {
    "id": "tool.chunk.grid_edit",
    "file": "index-DTKnr6h1.js",
    "line": 14,
    "ref": "index-DTKnr6h1.js:14",
    "excerpt": "      \"assets/page-Dps6Us_X.js\",",
    "status": "ok"
  },
  "tool.chunk.dca_edit": {
    "id": "tool.chunk.dca_edit",
    "file": "index-DTKnr6h1.js",
    "line": 249553,
    "ref": "index-DTKnr6h1.js:249553",
    "excerpt": "  hVe = nR(() => gu(() => import(\"./page-CAOt1VfL.js\"), []), P.jsx(iR, {})),",
    "status": "ok"
  }
} as const satisfies Record<string, EvidenceRef>;

/** UI copy only when claim is ok — audit fails otherwise. */
export function ui(id: keyof typeof CLAIMS, fallbackAssert = true): string {
  const c = CLAIMS[id];
  if (!c || c.status !== "ok" || c.line == null) {
    if (fallbackAssert) {
      throw new Error(`UI string missing evidence: ${String(id)}`);
    }
    return String(id);
  }
  // Prefer canonical value map for known ids (regex claims are not the display text).
  return UI_VALUES[id] ?? String(id);
}

/** Canonical display values extracted / verified against claim lines. */
export const UI_VALUES: Partial<Record<keyof typeof CLAIMS, string>> = {
  "ui.login.welcome": "Welcome Trader!",
  "ui.login.sign_in": "Sign in to continue.",
  "ui.login.backend_url": "Backend URL",
  "ui.login.username": "Username",
  "ui.login.password": "Password",
  "ui.login.submit": "Log in",
  "ui.nav.bots": "Bots",
  "ui.nav.strategies": "Strategies",
  "ui.nav.accounts": "Exchange Accounts",
  "ui.nav.settings": "Settings",
  "ui.settings.title": "App settings",
  "ui.msg.bot_created": "Bot created successfully",
  "ui.msg.bot_updated": "Bot updated successfully",
  "ui.msg.no_logs": "No logs yet",
  "ui.msg.account_created": "Account created",
  "ui.msg.account_checked": "Account checked",
  "ui.msg.add_exchange": "Add exchange account",
  "ui.msg.bot_settings": "Bot settings",
  "ui.msg.create": "Create",
  "ui.strategy.grid": "Grid Bot",
  "ui.strategy.dca": "DCA Bot",
  "form.default.symbol": "OKX:BTC/USDT",
  "meta.backend_default": "http://localhost:8000",
};

export const ROUTE_PATHS = [
  "/_layout/dashboard/accounts",
  "/_layout/dashboard/bot/",
  "/_layout/dashboard/bot/$id",
  "/_layout/dashboard/bot/create",
  "/_layout/dashboard/bot/edit/$id",
  "/_layout/dashboard/dca-bot/$id",
  "/_layout/dashboard/dca-bot/create",
  "/_layout/dashboard/dca-bot/edit/$id",
  "/_layout/dashboard/grid-bot/$id",
  "/_layout/dashboard/grid-bot/create",
  "/_layout/dashboard/grid-bot/edit/$id",
  "/_layout/dashboard/login",
  "/_layout/dashboard/settings",
  "/_layout/dashboard/strategies",
  "/dashboard/accounts",
  "/dashboard/bot",
  "/dashboard/bot/",
  "/dashboard/bot/$id",
  "/dashboard/bot/create",
  "/dashboard/bot/edit/$id",
  "/dashboard/dca-bot/$id",
  "/dashboard/dca-bot/create",
  "/dashboard/dca-bot/edit/$id",
  "/dashboard/grid-bot/$id",
  "/dashboard/grid-bot/create",
  "/dashboard/grid-bot/edit/$id",
  "/dashboard/login",
  "/dashboard/settings",
  "/dashboard/strategies"
] as const;
export const LAYOUT_KEYS = [
  "LayoutDashboardAccountsRoute",
  "LayoutDashboardBotCreateRoute",
  "LayoutDashboardBotEditIdRoute",
  "LayoutDashboardBotIdRoute",
  "LayoutDashboardBotIndexRoute",
  "LayoutDashboardDcaBotCreateRoute",
  "LayoutDashboardDcaBotEditIdRoute",
  "LayoutDashboardDcaBotIdRoute",
  "LayoutDashboardGridBotCreateRoute",
  "LayoutDashboardGridBotEditIdRoute",
  "LayoutDashboardGridBotIdRoute",
  "LayoutDashboardLoginRoute",
  "LayoutDashboardSettingsRoute",
  "LayoutDashboardStrategiesRoute"
] as const;
export const FORM_KEYS = [
  "barSize",
  "botName",
  "entryConditions",
  "entryOrderQuantity",
  "entryOrderType",
  "exchangeAccountId",
  "exchangeCode",
  "gridLines",
  "gridLinesNumber",
  "highPrice",
  "isDemoAccount",
  "lowPrice",
  "quantityPerGrid",
  "safetyOrderFormType",
  "safetyOrders",
  "stopLossEnabled",
  "stopLossPercent",
  "symbolId",
  "takeProfitPercent"
] as const;
export const RPC_PROCS = [
  "bot.activeSmartTrades",
  "bot.completedSmartTrades",
  "bot.create",
  "bot.delete",
  "bot.getBotLogs",
  "bot.getOne",
  "bot.getStrategies",
  "bot.list",
  "bot.openSmartTrades",
  "bot.start",
  "bot.stop",
  "bot.update",
  "candles.list",
  "candles.update",
  "dcaBot.create",
  "dcaBot.getOne",
  "dcaBot.getTrades",
  "exchangeAccount.check",
  "exchangeAccount.create",
  "exchangeAccount.delete",
  "exchangeAccount.getOne",
  "exchangeAccount.list",
  "exchangeAccount.update",
  "gridBot.getOne",
  "gridBot.list",
  "order.amend",
  "order.cancel",
  "order.cancelReplace",
  "order.closedOrders",
  "order.create",
  "order.deal",
  "order.exchangeOrderId",
  "order.id",
  "order.infiniteOrders",
  "order.modify",
  "order.openOrders",
  "order.place",
  "order.status",
  "order.subscribe",
  "order.test",
  "order.update",
  "public.bookTicker",
  "public.deals",
  "public.healhcheck",
  "public.increase",
  "public.json",
  "public.kline",
  "public.miniTicker",
  "public.miniTickers",
  "public.sandbox",
  "smartTrade.infiniteList",
  "smartTrade.list",
  "symbol.getOne",
  "symbol.list",
  "symbol.price"
] as const;

export const STORAGE_KEYS = {
  APP_URL: "APP_URL",
  ADMIN_PASSWORD: "ADMIN_PASSWORD",
  DEVELOPER_MODE_ENABLED: "DEVELOPER_MODE_ENABLED",
} as const;

export const PATHS = {
  login: "/dashboard/login",
  accounts: "/dashboard/accounts",
  settings: "/dashboard/settings",
  strategies: "/dashboard/strategies",
  botIndex: "/dashboard/bot/",
  botId: "/dashboard/bot/$id",
  botCreate: "/dashboard/bot/create",
  botEdit: "/dashboard/bot/edit/$id",
  gridCreate: "/dashboard/grid-bot/create",
  gridId: "/dashboard/grid-bot/$id",
  gridEdit: "/dashboard/grid-bot/edit/$id",
  dcaCreate: "/dashboard/dca-bot/create",
  dcaId: "/dashboard/dca-bot/$id",
  dcaEdit: "/dashboard/dca-bot/edit/$id",
} as const;

export const FILE_ROUTES = {
  layout: "/_layout",
  login: "/_layout/dashboard/login",
  accounts: "/_layout/dashboard/accounts",
  settings: "/_layout/dashboard/settings",
  strategies: "/_layout/dashboard/strategies",
  botIndex: "/_layout/dashboard/bot/",
  botId: "/_layout/dashboard/bot/$id",
  botCreate: "/_layout/dashboard/bot/create",
  botEdit: "/_layout/dashboard/bot/edit/$id",
  gridCreate: "/_layout/dashboard/grid-bot/create",
  gridId: "/_layout/dashboard/grid-bot/$id",
  gridEdit: "/_layout/dashboard/grid-bot/edit/$id",
  dcaCreate: "/_layout/dashboard/dca-bot/create",
  dcaId: "/_layout/dashboard/dca-bot/$id",
  dcaEdit: "/_layout/dashboard/dca-bot/edit/$id",
} as const;
